version: '3.8'

services:
  db:
    # Оця версія ПІДХОДИТЬ для вашого комп'ютера (amd64)
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dentistry_db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    # Це лікує помилку з I/O, яка у вас була
    sysctls:
      - fs.aio-max-nr=262144

  backend:
    build: ./backend
    container_name: dentistry_backend
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=master
      - DB_USER=sa
      - DB_PASSWORD=YourStrongPassword123!
      - DB_PORT=1433

  frontend:
    build: ./frontend
    container_name: dentistry_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mssql_data: